name: 'del-docker-tag'
description: 'Github actions for deleting the docker image tag of DockerHub'
author: 'xhofe'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  username:
    description: 'Username of docker hub'
    required: false
  password:
    description: 'Password of docker hub'
    required: false
  token:
    description: 'Token of docker hub'
    required: false
  tags:
    description: 'Tags of docker image'
    required: true

runs:
  using: node20
  main: dist/index.js
